spring:
  application:
    name: spring-rest
  datasource:
    url: jdbc:mysql://localhost:3306/cs544
    username: root
    password: secret
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  file:
    name: /Users/Faisal/Dumpster/Logging/${spring.application.name}/log
